feat: add additional to update contacts
AnastasiyaC/webix-jet-start pull request #2
Opened 2022-04-19 08:51 UTC by AnastasiyaC

2022-04-19 12:03 UTC, olimed reviewed
1) 
![image](https://user-images.githubusercontent.com/31127246/163996769-b0f40f3f-e9b4-41ae-b2fe-81d6e5ed0b5a.png)
2) 
![image](https://user-images.githubusercontent.com/31127246/163996816-10c89ad4-8843-473b-a74b-c141735079c7.png)
3) по нажатию на кнопку Cancel ничего не происходит
4) добавить к списку переводов все кнопки, заголовки, лэйблы и т.д.

2022-04-19 12:03 UTC, olimed commented on sources/views/startViews/contactsLst.js
> +		this.setIdParam(list);
не обязательно передавать `list`, это внутренняя вьюшка и в методе `setIdParam` к ней есть доступ

2022-04-19 12:03 UTC, olimed commented on sources/views/startViews/contactsLst.js
> +		contactsCollection.add(newContact);
`add()` возвращает `id`, поэтому можешь сохранить возвращаемое значение и его использовать при `select` в листе

2022-04-19 15:57 UTC, HelgaListopad requested changes

2022-04-19 15:57 UTC, HelgaListopad commented on sources/views/startViews/contactsLst.js
> +	init() {
В этом модуле остаётся незакрытым вариант, когда юзер убрал id из адресной строки. Это можно проследить в `urlChange` (комментарий на этой строке кода оставляю для своего удобства)

Сейчас в таком случае форма корректно чистится, а вот селект остаётся на таблице.

2022-04-20 07:28 UTC, HelgaListopad requested changes

2022-04-20 07:28 UTC, HelgaListopad commented on sources/views/startViews/contactsLst.js
> +		list.unselect(list.getSelectedId());
Можно сделать через один метод - unselectAll
https://docs.webix.com/api__link__ui.list_unselectall.html

2022-04-20 07:28 UTC, HelgaListopad commented on sources/views/startViews/contactsForm.js
> +						onFocus: () => {
Мне кажется, сбрасывать валидацию по фокусу - это лишнее 
Например, если у полей есть invalidMedsage, то их высота в форме может некрасиво скакать в таком случае.
Но если
- нет invalidMedsage
- у полей нет других своих событий в on
- у всех полей есть onFocus

То запись можно сократить, перенеся всё в elementsConfig формы
https://snippet.webix.com/noe8ive9

https://docs.webix.com/desktop__common_config.html

2022-04-20 07:41 UTC, olimed reviewed
![image](https://user-images.githubusercontent.com/31127246/164175411-6a3b3fc7-871c-4cfb-86c3-7f18227e6755.png)
пропало удаление

2022-04-20 08:13 UTC, olimed approved these changes

2022-04-20 09:12 UTC, HelgaListopad requested changes

2022-04-20 09:12 UTC, HelgaListopad commented on sources/views/startViews/contactsForm.js
> +						this.clearFormValidation();
Всё же сделай проверку на `name`
Сбобытие будет задано для вообще всех элементов формы, включая кнопки - а нам не надо вызывать лишний раз `clearValidation` на Save

2022-04-20 09:37 UTC, HelgaListopad approved these changes

2022-04-20 09:37 UTC, merged