feat: sync ui elements with collections
AnastasiyaC/webix-jet-start pull request #3
Opened 2022-04-20 10:08 UTC by AnastasiyaC

2022-04-20 12:27 UTC, HelgaListopad requested changes

2022-04-20 12:27 UTC, HelgaListopad commented on sources/views/startViews/contactsLst.js
> +						const status = statusesCollection.getItem(obj.Status);
В случае, если контакты загрузились, а страны и статусы ещё нет, эти две строчки вернут undefined и будут так делать, пока данные не придут, а лист не будет перерисован.

Ниже ты верно проверяешь наличие стран и статусов, но чтобы отрисовать данные правильно, добавь на init вызов `list.refresh()` после того, как данные в эти коллекции загрузятся
```js
list.sync(contactsCollection);
webix.promise.all([
	countriesCollection.waitData,
	statusesCollection.waitData
]).then( () => list.refresh() );
```

2022-04-20 12:27 UTC, HelgaListopad commented on sources/views/startViews/contactsLst.js
> +			list.select(list.getLastId());
Добавлять новую строку можно с любым индексом. 
Посмотри аргументы, которые приходят в then - там должно быть id новой строки

2022-04-20 21:34 UTC, olimed approved these changes

2022-04-22 10:10 UTC, HelgaListopad approved these changes

2022-04-22 10:10 UTC, merged